### ISSUE TITLE
__builtin_constant_p behaviour across compilers

### ISSUE THREAD

**Issue by trudeaun** [nemequ/attic#1]
I believe that in order to see whether the value of a macro's operand can be determined to be a constant, 2 different implementations have been done for GCC and XL compilers at https://github.com/nemequ/attic/blob/master/is_constant.h. 

For GCC, `__builtin_constant_p` is used, and for XL, the `IS_CONSTEXPR` macro is used. Is this done because XL's implementation of `__builtin_constant_p` does not work as expected? @nemequ

**Comment by nemequ** [comment]
Sorry, I ended up rambling a bit. There is a fair amount of information in here, and I don't have time to better organize it right now :(

> I believe that in order to see whether the value of a macro's operand can be determined to be a constant, 2 different implementations have been done for GCC and XL compilers at https://github.com/nemequ/attic/blob/master/is_constant.h.

Kind of. There is a somewhat subtle distinction between the `IS_CONSTEXPR` and `IS_CONSTANT` macros. `IS_CONSTEXPR` checks to see if the argument is an integer constant expression. `IS_CONSTANT` checks to see if the argument is known to the compiler at compile time, regardless of whether the standard says it is an integer constant expression or not. In other words, `IS_CONSTEXPR` will return true for a subset of what `IS_CONSTANT` will.

`IS_CONSTANT` should be used for optimizations. For example, if you want to choose between a code path which can be constant folded by the compiler but would be relatively slow to execute at runtime and one which is effectively a black box to the compiler but is relatively fast at runtime, you should use `IS_CONSTANT`.

`IS_CONSTEXPR` is useful if you want to ensure a value is an integer constant expression as dictated by the C standard. A good example is the `REQUIRE_CONSTEXPR` macro in that header, which is defined as `(IS_CONSTEXPR(expr) ? (expr) : (-1))` (when `IS_CONSTEXPR` is available). This can then be used to protect against creating a VLA, since an array is variable-length when the length is not an ICE.

Since `IS_CONSTEXPR` is a subset of `IS_CONSTANT`, it can be used as a fallback when a compiler supports that insane macro but not `__builtin_constant_p`, which is what this header does. In such cases you may miss some optimizations on some platforms (when `__builtin_constant_p` would, if it were implemented, return true but the expression is *not* a constant expression).

So basically, `IS_CONSTEXPR` should always work for C11 thanks to `_Generic` (although it's [broken on suncc](https://community.oracle.com/thread/4139563)). For pre-C11, it's defined to that crazy macro for compilers which are known to work (it depends on `sizeof(void)` working, which is non-standard). Otherwise it's undefined. Note that no compilers I'm aware of support it in C++ mode; I'm not aware of a way to check for an ICE in C++.

`IS_CONSTANT` is defined to `__bulitin_constant_p` where that builtin is known to work, otherwise it falls back on `IS_CONSTEXPR` if it is available, otherwise return false.

> For GCC, `__builtin_constant_p` is used, and for XL, the `IS_CONSTEXPR` macro is used. Is this done because XL's implementation of `__builtin_constant_p` does not work as expected?

AFAICT `__builtin_constant_p` is undocumented in XL C/C++; I would expect it to be in the *Supported GCC non-vector built-in functions* section in chapter 8 of the compiler reference. Without that it's difficult to tell when `__builtin_constant_p` support first appeared, and I don't have access to older versions of XL C/C++ to test for myself.

With that in mind, I'm don't think it makes sense to explicitly check for XL C/C++ (or, even better, the version number at which `__builtin_constant_p` was added). The only sensible thing seems to be relying on the `__GNUC__` / `__GNUC_MINOR__` macros which are defined by XL C/C++ for compatibility with gcc/g++. `__builtin_constant_p` was added to GCC with version 3.1, and XL C/C++ currently masquerades as 4.2, so `__builtin_constant_p` *should* be used even without explicitly checking for XL C/C++.

**Comment by trudeaun** [comment]
@nemequ Thanks for this detailed response! I'll look into getting `__builtin_constant_p` documented for XLC. I was interested to know if you were running into any trouble with XL's implementation of `__builtin_constant_p`. If you run into any issues in the future, please let me know! I think we can close this issue off now.

**Comment by nemequ** [comment]
@trudeaun while you're at it, AFAICT `__builtin_types_compatible_p` is also undocumented. It works in 13.1.6 and is available in GCC ≥ 3.1, though.
