### ISSUE TITLE
Doesn't seem to work for me

### ISSUE THREAD

**Issue by robertramey** [nemequ/attic#2]
I'm really interesting in this.  But I'm not getting it to work.  Here is simple example:
`
#include "is_constant.h"
#include <iostream>

constexpr int test(int i){
    return __builtin_constant_p(i);
    // return IS_CONSTANT(i);
}

constexpr int test2(int i){
    return 0;
    // return IS_CONSTEXPR(i);
}

int main(){
    int x = 42;
    constexpr int y = 42;
    std::cout << x << ' ' << test(x) << ' ' << test2(x) << '\n';
    std::cout << x << ' ' << test(y) << ' ' << test2(y) << '\n';
    std::cout << x << ' ' << test(42) << ' ' << test2(x) << '\n';
    return 0;
}
`
displays the following on execution Clang and gcc 7.1 :
`
42 0 0
42 0 0
42 0 0
`
Also IS_CONSTANT generated a syntax error.
Also I'm not sure if this is expect to work for constexpr values or any values.

**Comment by robertramey** [comment]
t.cpp: In function ‘constexpr int test2(int)’:
is_constant.h:80:19: warning: invalid application of ‘sizeof’ to a void type [-Wpointer-arith]
        sizeof(void) != \
                   ^
t.cpp:11:12: note: in expansion of macro ‘IS_CONSTEXPR’
     return IS_CONSTEXPR(i);
            ^~~~~~~~~~~~
is_constant.h:84:21: error: types may not be defined in casts
            ((struct { char v[sizeof(void) * 2]; } *) 1) \
                     ^
t.cpp:11:12: note: in expansion of macro ‘IS_CONSTEXPR’
     return IS_CONSTEXPR(i);
            ^~~~~~~~~~~~
is_constant.h:84:41: warning: invalid application of ‘sizeof’ to a void type [-Wpointer-arith]
            ((struct { char v[sizeof(void) * 2]; } *) 1) \
                                         ^
t.cpp:11:12: note: in expansion of macro ‘IS_CONSTEXPR’
     return IS_CONSTEXPR(i);
            ^~~~~~~~~~~~
is_constant.h:85:10: error: ‘void*’ is not a pointer-to-object type
          ) \
          ^
t.cpp:11:12: note: in expansion of macro ‘IS_CONSTEXPR’
     return IS_CONSTEXPR(i);
            ^~~~~~~~~~~~

**Comment by nemequ** [comment]
The header in this repo is designed for C, not C++.  If you want C++ compatibility, you might want to consider [the version in Hedley](https://nemequ.github.io/hedley/api-reference.html#HEDLEY_IS_CONSTANT).  Sorry, I really could have spent more time on the documentation.

The more interesting problem, though, is the different types of "constant" that you seem to be conflating, which is really easy to do; I didn't fully understand the distinction before I started diving into this code to try and figure out how the hell this macro worked.  Integer constant expressions are defined by the C specification (see § 6.6 of C11), and `x` isn't one.  The `IS_CONSTEXPR` macro in this repo is designed to test for integer constant expressions.

I'm not aware of a good way to check for an ICE in C++. [This SO answer](https://stackoverflow.com/a/40413051) is the closest I've seen, but it results in quite a bit of noise in the code.

`__builtin_constant_p()` is more lenient, and seems closer to what you're expecting.  Instead of checking for an ICE, it just returns true if the compiler knows that a value is always known at compile-time, but keep in mind that there may be false negatives (though no false positives).  Unfortunately, `__builtin_constant_p()` isn't portable.

So, the idea here is for `IS_CONSTANT` is to provide a best-effort check in the spirit of `__builtin_constant_p()`.  It will use `__builtin_constant_p()` if it can, otherwise it will fall back on checking for an ICE (if possible) as a more portable fallback.  It's still not completely portable, though; C++ doesn't like it, and C prior to C11 requires `sizeof(void)`, which is a common though not universal extension to C.  Therefore, just like `__builtin_constant_p()`, there may be false negatives.

Looking at the version in Hedley (which is a bit of an improvement on this code), what you end up with is `__builtin_constant_p()` for some compilers (GCC, ICC, TinyCC, armcc, and xlcc), including several C++ compilers.  After that, it's C-only; a C11 version for when compilers are in C11 mode (though Oracle Developer Studio and PGI have bugs which prevent it from working, I've reported them) or otherwise known to support `_Generic`.  If that doesn't work, compilers known to support `sizeof(void)` fall back on the crazy macro.

On another subject, if you want to put a block of code in markdown, you can enclose it in three backticks on either side instead of one.  It wasn't hard to get your code working (well, not working) or anything, just thought you might want to know for the future :)

**Comment by nemequ** [comment]
FWIW, issue #1 also has an explanation which may help.

**Comment by robertramey** [comment]
thanks for spending time with this.  I spent a little more time with this and made a more serious effort to determine what's going on.
```C++
#include <iostream>

#include "is_constant.h"

#define test_macro1(i) \
    IS_CONSTANT(i)

#define test_macro2(i) \
    __builtin_constant_p((i))

inline int test1(const int & i){
    return IS_CONSTANT(i);
}

inline int test2(int i){
    return IS_CONSTANT(i);
}

template<typename I>
inline int test3(I i){
    return IS_CONSTANT(i);
}

template<typename I>
constexpr inline int test4(I i){
    return IS_CONSTANT(i);
}

#define display(i)                 \
    std::cout                      \
        << i << ' '                \
        << test_macro1(i) << ' '   \
        << test_macro2(i)  << ' '  \
        << test1(i)  << ' '        \
        << test2(i)  << ' '        \
        << test3(i)  << ' '        \
        << test4(i)  << ' '        \
      <<'\n';

int main(){
    int x = 42;
    display(x);

    constexpr const int y = 42;
    display(y);

    display(42);

    return 0;
}
```

which I build and run with:
g++ -std=c++14 -O1  -o t t.cpp; t

This lets me test a large number of combinations of O switches with minimal hassle.  
This always results in:
`
42 0 0 0 0 0 0 
42 1 1 0 0 0 0 
42 1 1 0 0 0 0 
`
Which indicates that the "constant ness" doesn't pass through via function arguments regardless of the usage of inline, delayed template instantiation or whatever.  One stack overflow poster has cited the gcc documentation:

However, if you use it in an inlined function and pass an argument of the function as the argument to the built-in, GCC will never return 1 when you call the inline function with a string constant or compound literal (see Compound Literals) and will not return 1 when you pass a constant numeric value to the inline function unless you specify the -O option.

So it looks like we're out of luck here.
